export const ADD_SUSCRIPTION = "ADD_SUSCRIPTION";
export const ADD_SUSCRIPTION_SUCCESS = "ADD_SUSCRIPTION_SUCCESS";
export const ADD_SUSCRIPTION_ERROR = "ADD_SUSCRIPTION_ERROR";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
