export const ADD_SUSCRIPTION = "ADD_SUSCRIPTION";
export const ADD_SUSCRIPTION_SUCCESS = "ADD_SUSCRIPTION_SUCCESS";
export const ADD_SUSCRIPTION_ERROR = "ADD_SUSCRIPTION_ERROR";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const ADD_SUSCRIPTION_EDIT = "ADD_SUSCRIPTION_EDIT";
export const SUSCRIPTION_EDIT_SUCCESS = "ADD_SUSCRIPTION_EDIT_SUCCESS";

export const CHANGE_ACTION = "CHANGE_ACTION";

export const DELETE_SUSCRIPTION = "DELETE_SUSCRIPTION";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
